# vim: set filetype=yaml.ansible :
---
# The name will be used for the domain name of the cluster as well
cluster:
  name: lab
  domain: cluster.io

  # name of the user that will be used on all machines
  user: hanapedia

  # name of the user in vms
  node_user: ubuntu

vlan:
  # Default VLAN ID, configured on the network switch
  id: 4

  # The subnet of VLAN
  subnet: 192.168.100.0/24

  # The IP address of the VLAN gateway configured on the network switch
  gateway: 192.168.100.2

  dns_dhcp:
    # Static IP address assigned to lab1, which serves DHCP/DNS
    server_ip: 192.168.100.3

    # Lower bound for address pool
    lower_bound_ip: 192.168.100.11

    # Upper bound for address pool
    upper_bound_ip: 192.168.100.100

    # forward unresolved dns queries to this ip
    forward: 8.8.8.8

bridge:
  # The name of the bridge to be used by the virtual network
  name: br0

# Kubernetes configuration
k8s:
  # version of kubernetes
  version: '1.27'

  # cri to use. only crio supported
  cri: crio

  # control plane master node
  cp_master: cp-lab2

  # control plane master node
  cp_address: 192.168.100.5

  # loadbalancer node
  loadbalancer: lab2

  # cni to use. flannel, *calico, *cilium
  cni: flannel

  # storage plugin to use. openebs
  storage_plugin: openebs
