# vim: set filetype=yaml.ansible :
---
- hosts: nodes
  name: Setup Kubectl
  become: true
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Install iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present

    - name: Enable iscsid
      ansible.builtin.service:
        name: iscsid
        enabled: true
        state: started

    - name: Create hostpath directory for local
      ansible.builtin.file:
        path: "/var/openebs/local"
        state: directory
        mode: "0755"

- hosts: localhost
  name: Setup kube plugins
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ localhost_sudo_password }}"
  gather_facts: false
  tasks:
    # - name: Establish SSH tunnel
    #   ansible.builtin.command:
    #     argv:
    #       - ssh
    #       - -fNL
    #       - "6443:{{ k8c.cp_master }}:6443"
    #       - -J
    #       - lab2
    #       - -i
    #       - "{{ identity_file_path }}"
    #       - -o
    #       - IdentitiesOnly=yes
    #       - "{{ cluster.node_user }}@{{ k8s.cp_master }}"
    #   changed_when: true

    # - name: Include role to setup CNI
    #   ansible.builtin.include_role:
    #     name: setup_cni
    #   vars:
    #     cni_plugin: "{{ k8s.cni }}"
    #     kube_config_path: "{{ local_kubeconfig_path }}"

    - name: Include role to setup storage
      ansible.builtin.include_role:
        name: setup_storage
      vars:
        storage_plugin: "{{ k8s.storage_plugin }}"
        kube_config_path: "{{ local_kubeconfig_path }}"
