# vim: set filetype=yaml.ansible :
---
- hosts: nodes
  name: Prerequisite for openebs
  become: true
  tasks:
    - name: Setup Kubectl
      when: cp
      block:
        - name: Include role to setup kubectl
          ansible.builtin.include_role:
            name: setup_kubectl


- hosts: localhost
  name: Setup CNI
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ localhost_sudo_password }}"
  gather_facts: false
  tasks:
    - name: Replace the server address in kubeconfig
      ansible.builtin.replace:
        path: "{{ local_kubeconfig_path }}"
        regexp: '^\s*server: https://{{ k8s.cp_master }}:6443'
        replace: '    server: https://kubernetes:6443'

    - name: Add Kubernetes to /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: '127.0.0.1 kubernetes'
        state: present
