# vim: set filetype=yaml.ansible :
---
- hosts: nodes
  name: Reset kubeadm command
  become: true
  tasks:
    - name: Destroy k8s cluster
      when: not cp
      ansible.builtin.command: kubeadm reset -f
      changed_when: true

    - name: Destroy k8s cluster
      when: cp
      ansible.builtin.command: kubeadm reset -f
      changed_when: true

    - name: Remove flannel cni config
      when: cp
      ansible.builtin.file:
        path: "/etc/cni/net.d/10-flannel.conflist"
        state: absent
