# vim: set filetype=yaml.ansible :
---
- hosts: physical_machines
  name: Setup loadbalancer
  become: true
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Include role to setup loadbalancer
      when: k8s.ha_control_plane and loadbalancer
      ansible.builtin.include_role:
        name: setup_cp_lb
      vars:
        lb_interface_name: "{{ bridge.name }}"

- hosts: nodes
  name: Initiate kubernetes cluster
  become: true
  tasks:
    - name: Setup master node
      when: k8s.ha_control_plane and cp and master
      block:
        - name: Set fact with the name of loadbalancer
          ansible.builtin.set_fact:
            loadbalancer_node: "{{ item }}"
          when: hostvars[item].loadbalancer | default(false) | bool
          loop: "{{ groups['physical_machines'] }}"

        - name: Include role to setup master control plane node
          ansible.builtin.include_role:
            name: setup_cp_master_node
          vars:
            cluster_name: "{{ cluster.name }}"
            cp_master: "{{ k8s.cp_master }}"
            control_plane_endpoint: "{{ loadbalancer_node }}"

- hosts: nodes
  name: Join kubernetes cluster control plane nodes
  become: true
  tasks:
    - name: Setup other control plane nodes
      when: k8s.ha_control_plane and cp and not master
      block:
        - name: Set fact with the name of loadbalancer
          ansible.builtin.set_fact:
            loadbalancer_node: "{{ item }}"
          when: hostvars[item].loadbalancer | default(false) | bool
          loop: "{{ groups['physical_machines'] }}"

        - name: Include role to join control plane node
          ansible.builtin.include_role:
            name: setup_cp_node
          vars:
            cp_master: "{{ k8s.cp_master }}"
            control_plane_endpoint: "{{ loadbalancer_node }}"

- hosts: nodes
  name: Join kubernetes cluster worker nodes
  become: true
  tasks:
    - name: Setup worker nodes
      when: k8s.ha_control_plane and not cp
      block:
        - name: Set fact with the name of loadbalancer
          ansible.builtin.set_fact:
            loadbalancer_node: "{{ item }}"
          when: hostvars[item].loadbalancer | default(false) | bool
          loop: "{{ groups['physical_machines'] }}"

        - name: Include role to join worker node
          ansible.builtin.include_role:
            name: setup_worker_node
          vars:
            cp_master: "{{ k8s.cp_master }}"
            control_plane_endpoint: "{{ loadbalancer_node }}"
