# vim: set filetype=yaml.ansible :
---
- hosts: physical_machines
  name: Make sure loadbalancer is off
  become: true
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Diable loadbalancer
      when: not k8s.ha_control_plane and cp
      block:
        - name: Include role to disable loadbalancer
          ansible.builtin.include_role:
            name: reset_cp_lb

- hosts: physical_machines
  name: Initiate kubernetes cluster
  become: true
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Setup master node
      when: not k8s.ha_control_plane and cp
      block:
        - name: Include role to setup master control plane node
          ansible.builtin.include_role:
            name: setup_cp_master_node
          vars:
            cluster_name: "{{ cluster.name }}"
            cp_master: "{{ k8s.cp_master }}"
            control_plane_endpoint: "{{ k8s.cp_master }}"

- hosts: nodes
  name: Join kubernetes cluster worker nodes
  become: true
  tasks:
    - name: Setup worker nodes
      when: not k8s.ha_control_plane
      block:
        - name: Include role to join worker node
          ansible.builtin.include_role:
            name: setup_worker_node
          vars:
            cp_master: "{{ k8s.cp_master }}"
            control_plane_endpoint: "{{ k8s.cp_master }}"
