# vim: set filetype=yaml.ansible :
---
- hosts: physical_machines
  name: Prepare vm configuration
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Include role to setup vm on physical machines
      ansible.builtin.include_role:
        name: reset_node
