# vim: set filetype=yaml.ansible :
---
- hosts: physical_machines
  name: Setup VLAN on network interface
  become: true
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Include role to setup vlan
      when: not dns_dhcp
      ansible.builtin.include_role:
        name: setup_vlan
      vars:
        # Default VLAN ID, configured on the network switch
        vlan_id: "{{ vlan.id }}"

        # The IP address of the VLAN gateway configured on the network switch
        vlan_gateway: "{{ vlan.gateway }}"

        # The IP address that will be assigned to the vlan interface
        vlan_ip: "{{ ip_address }}"

        # The name of interface that vlan will use
        vlan_interface: "{{ interface_name }}"
