# vim: set filetype=yaml.ansible :
---
- hosts: physical_machines
  name: Common setup on the physical machines 
  become: true
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Include role to run the common setup
      ansible.builtin.include_role:
        name: setup_common
