# vim: set filetype=yaml.ansible :
---
- name: Configure openebs
  when: storage_plugin == 'openebs'
  block:
    - name: Make sure download destination exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/out/k8s/openebs/"
        state: directory
        mode: '0755'

    - name: Download openebs manifest
      ansible.builtin.get_url:
        url: "{{ openebs.repo }}"
        dest: "{{ playbook_dir }}/out/k8s/openebs/kube-openebs.yaml"
        mode: "0755"

    - name: Apply openebs manifests to the cluster.
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/out/k8s/openebs/kube-openebs.yaml"
        kubeconfig: "{{ kube_config_path }}"
        wait: true
