# vim: set filetype=yaml.ansible :
---
- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
