# vim: set filetype=yaml.ansible :
---
- name: Create bridge interface
  community.general.nmcli:
    conn_name: "{{ bridge_name }}"
    type: bridge
    ip4: "{{ vlan_ip ~ '/24' }}"
    gw4: "{{ vlan_gateway }}"
    dns4: "{{ leader_ip_address }} 8.8.8.8 8.8.4.4"
    state: present
    autoconnect: true

- name: Create VLAN interface on physical machine
  community.general.nmcli:
    conn_name: "{{ vlan_interface }}.{{ vlan_id }}"
    type: vlan
    state: present
    vlanid: "{{ vlan_id }}"
    vlandev: "{{ vlan_interface }}"
    master: "{{ bridge_name }}"
    slave_type: bridge
    autoconnect: true
