# vim: set filetype=yaml.ansible :
---
- name: Common setup
  block:
    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - "vlan"
          - "network-manager"
        state: present

    - name: Load 8021q module for VLAN
      ansible.builtin.modprobe:
        name: 8021q
        state: present

    - name: Add 8021q to /etc/modules
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: 8021q

    - name: Ensure NetworkManager configuration directory exists
      ansible.builtin.file:
        path: /etc/NetworkManager/conf.d
        state: directory
        mode: "0640"

    - name: Configure NetworkManager to manage all devices
      ansible.builtin.copy:
        src: 10-device.conf
        dest: /etc/NetworkManager/conf.d/10-device.conf
        mode: "0640"
      notify:
        - Restart NetworkManager

    - name: Manage the network interface with NetworkManager
      changed_when: true
      ansible.builtin.command:
        cmd: "nmcli device set {{ vlan_interface }} managed yes"

- name: DNS DHCP setup
  when: dns_dhcp
  block:
    - name: Import dns_dhcp tasks
      ansible.builtin.import_tasks: leader.yaml

- name: Follower setup
  when: not dns_dhcp
  block:
    - name: Import follower tasks
      ansible.builtin.import_tasks: follower.yaml
