# vim: set filetype=yaml.ansible :
---
- name: Restart watchdog
  ansible.builtin.systemd:
    name: watchdog
    state: restarted

- name: Restart libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
