# vim: set filetype=yaml.ansible :
---
- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ guest_os_packages }}"
    state: present

- name: Import cri tasks
  ansible.builtin.import_tasks: cri.yaml

- name: Import kube tasks
  ansible.builtin.import_tasks: kube.yaml
