# vim: set filetype=yaml.ansible :
---
- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ os_packages }}"
    state: present
