# vim: set filetype=yaml.ansible :
---
- name: Ensure NetworkManager configuration directory exists
  ansible.builtin.file:
    path: /etc/NetworkManager/conf.d
    state: directory
    mode: "0640"

- name: Configure NetworkManager for local DNS
  ansible.builtin.copy:
    src: local_dns.conf
    dest: /etc/NetworkManager/conf.d/local_dns.conf
    mode: "0640"
  notify:
    - Restart NetworkManager

- name: Configure network interface to use localhost DNS server
  nmcli:
    conn_name: "{{ vlan_interface }}.{{ vlan_id }}"
    dns4: 127.0.0.1
    state: present
