# vim: set filetype=yaml.ansible :
---
- name: Ensure that destination directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/kvm-provisioner"
    state: directory
    mode: "0755"

- name: Destroy target Terraform
  ansible.builtin.command:
    cmd: "terraform destroy -auto-approve -var-file={{ target }}.tfvars"
    chdir: "{{ ansible_env.HOME }}/kvm-provisioner/{{ target }}"
