# vim: set filetype=yaml.ansible :
---
- hosts: followers
  name: Setup VLAN on network interface
  become: true
  vars_files:
    - ./vars/secret.yaml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Set fact with IP address of leader physical_machines
      ansible.builtin.set_fact:
        leader_ip_address: "{{ hostvars[item].ip_address }}"
      when: hostvars[item].leader | default(false) | bool
      loop: "{{ groups['leaders'] }}"

    - name: Include role to setup vlan
      when: not leader
      ansible.builtin.include_role:
        name: setup_vlan
      vars:
        # Default VLAN ID, configured on the network switch
        vlan_id: "{{ vlan.id }}"

        # The IP address of the VLAN gateway configured on the network switch
        vlan_gateway: "{{ vlan.gateway }}"

        # The IP address that will be assigned to the vlan interface
        vlan_ip: "{{ ip_address }}"

        # The name of interface that vlan will use
        vlan_interface: "{{ interface_name }}"

    - name: Include role to use dhcp/dns server on follower machines
      when: not leader
      ansible.builtin.include_role:
        name: setup_dnsmasq_client
      vars:
        # forward unresolved dns queries to this ip
        forward_dns_server_ip: "{{ vlan.dns_dhcp.forward }}"
        # Default VLAN ID, configured on the network switch
        vlan_id: "{{ vlan.id }}"

        # The IP address of the VLAN gateway configured on the network switch
        vlan_gateway: "{{ vlan.gateway }}"

        # The IP address that will be assigned to the vlan interface
        vlan_ip: "{{ ip_address }}"

        # The name of interface that vlan will use
        vlan_interface: "{{ interface_name }}"
