# vim: set filetype=yaml.ansible :
---
all:
  children:
    physical_machines:
      children:
        leaders:
        followers:
    leaders:
      hosts:
        lab1:
    followers:
      hosts:
        lab2:
