# vim: set filetype=yaml.ansible :
---
- name: Create bridge interface
  community.general.nmcli:
    conn_name: "{{ bridge_name }}"
    type: bridge
    method4: auto
    state: present
    autoconnect: true

- name: Add vlan interface to the bridge
  community.general.nmcli:
    conn_name: "{{ vlan_interface }}.{{ vlan_id }}"
    type: vlan
    method4: auto
    dns4: "{{ leader_ip_address }}"
    master: "{{ bridge_name }}"
    slave_type: bridge
    state: present
    autoconnect: true
