# vim: set filetype=yaml.ansible :
---
- name: Delete bridge interface
  community.general.nmcli:
    conn_name: "{{ bridge_name }}"
    state: absent

- name: Delete VLAN interface on physical machine
  community.general.nmcli:
    conn_name: "{{ vlan_interface }}.{{ vlan_id }}"
    state: absent
