# vim: set filetype=yaml.ansible :
---
- name: Copy firewalld zone configuration
  ansible.builtin.template:
    src: internal.xml.j2
    dest: /etc/firewalld/zones/internal.xml
    owner: root
    group: root
    mode: "0644"

- name: Reload firewalld to apply changes
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Ensure firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
